### ISSUE TITLE
Week 5 : Experiment Missing

### ISSUE THREAD

**Issue by rishi11** [dbharathkumar08/CS5610-dbharath#1]
There should be at-least 5 experiments each week.

**Comment by dbharathkumar08** [comment]
HI Rishi,
  I talked with the professor, since I was on leave I couldn't keep up with the pace. I have told him that I would catch up with week 5 and week 6 experiments.As written in my mail earlier.

Regards,
Bharath kumar D

**Comment by jannunzi** [comment]
That’s fine. Rishi, give Bharath an extra week to catch up.

Thanks, Jose

**Comment by dbharathkumar08** [comment]
It has been completed.
Regards,
Bharath kumar D
