### ISSUE TITLE
No Experiments This Week.

### ISSUE THREAD

**Issue by rishi11** [dbharathkumar08/CS5610-dbharath#2]
You have to perform 5 experiments each week, But I cannot find any. Please perform atleast 5 experiments for this week.

**Comment by dbharathkumar08** [comment]
HI Rishi,
  I talked with the professor, since I was on leave I couldn't keep up with the pace. I have told him that I would catch up with week 5 and week 6 experiments.As written in my mail earlier.

Regards,
Bharath kumar D

**Comment by dbharathkumar08** [comment]
It has been completed.
Regards,
Bharath kumar D
