### ISSUE TITLE
Week 7 - Experiment 5 - Functionality either not working or hard to understand.

### ISSUE THREAD

**Issue by rishi11** [dbharathkumar08/CS5610-dbharath#5]
In the experiments I am trying to enter my name in text field but not able to get suggestions. Please let me know am I wrong or should I try some other input

**Comment by dbharathkumar08** [comment]
It has a set of names in the asp file. If the name corresponds to that only then it will be displayed. otherwise you wont get any suggestion. Suggestions are based on the names stored in asp file.

Thank you,
Bharath kumar D

**Comment by rishi11** [comment]
Please mention those names somewhere on the page so that I can check the functionality.

**Comment by dbharathkumar08** [comment]
I have added in my description part of the HTML.
Thank you,
Bharath kumar D
